name: develop
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: 1.0.0-alpha.1.${{ github.run_id }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.202'

      - name: Build project
        run: ./scripts/build.sh

      - uses: nunit/docfx-action@v3.4.2
        name: Build Documentation
        with:
          args: ./docs/docfx.json

      - name: Pack nugets
        run: ./scripts/pack_nugets.sh

      - name: Pack
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: ./scripts/publish_unitypckage.sh

      - name: Upload Unitypackage Build
        uses: actions/upload-artifact@v4
        with:
          name: UdpToolkit.unitypackage
          if-no-files-found: error
          path: ./unity_package/UdpToolkit.${{ env.PACKAGE_VERSION }}.unitypackage

      - name: Upload Nuget packages
        uses: actions/upload-artifact@v4
        with:
          name: NugetPackages
          if-no-files-found: error
          path: ./**/*.nupkg
          
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          if-no-files-found: error
          path: ./docs/_site/